#include <fstream>

#include "src/circular_list.h"
#include "tests/3rdparty/googletest/googletest/include/gtest/gtest.h"

TEST(circular_list, All) {
  CircularList<int> list;

  list.Print();
  EXPECT_TRUE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(0));
  EXPECT_FALSE(list.Remove(2));
  EXPECT_FALSE(list.Find(2));
  EXPECT_EQ(list.Index(), -1);
  list.Insert(3);
  list.Print();
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(1));
  EXPECT_EQ(list.Index(), 0);
  EXPECT_FALSE(list.Find(2));
  EXPECT_TRUE(list.Find(3));
  list.Insert(3);
  list.Print();
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(2));
  EXPECT_EQ(list.Index(), 0);
  EXPECT_FALSE(list.Find(2));
  EXPECT_TRUE(list.Find(3));
  list.Clear();
  list.Print();
  EXPECT_TRUE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(0));
  EXPECT_EQ(list.Index(), -1);
  EXPECT_FALSE(list.Find(2));
  EXPECT_FALSE(list.Find(3));
  int item = -1;
  list.Next(&item);
  EXPECT_EQ(item, -1);
  list.Insert(3);
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(1));
  EXPECT_EQ(list.Index(), 0);
  EXPECT_FALSE(list.Find(2));
  EXPECT_TRUE(list.Find(3));
  list.Next(&item);
  EXPECT_EQ(item, 3);
  list.Next(&item);
  EXPECT_EQ(item, 3);
  list.Insert(3);
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(2));
  EXPECT_EQ(list.Index(), 0);
  EXPECT_FALSE(list.Find(2));
  EXPECT_TRUE(list.Find(3));
  list.Next(&item);
  EXPECT_EQ(item, 3);
  list.Next(&item);
  EXPECT_EQ(item, 3);
  list.Insert(2);
  list.Print();
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(3));
  EXPECT_EQ(list.Index(), 0);
  EXPECT_TRUE(list.Find(2));
  EXPECT_TRUE(list.Find(3));
  list.Next(&item);
  EXPECT_EQ(list.Index(), 1);
  EXPECT_EQ(item, 3);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 2);
  EXPECT_EQ(item, 2);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 0);
  EXPECT_EQ(item, 3);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 1);
  EXPECT_EQ(item, 3);
  list.Insert(14);
  EXPECT_TRUE(list.Find(2));
  EXPECT_TRUE(list.Find(3));
  EXPECT_TRUE(list.Find(14));
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(4));
  EXPECT_EQ(list.Index(), 1);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 2);
  EXPECT_EQ(item, 2);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 3);
  EXPECT_EQ(item, 14);
  EXPECT_TRUE(list.Find(2));
  EXPECT_TRUE(list.Find(3));
  EXPECT_TRUE(list.Find(14));
  EXPECT_FALSE(list.Find(13));
  list.Insert(13);
  EXPECT_TRUE(list.Find(2));
  EXPECT_TRUE(list.Find(3));
  EXPECT_TRUE(list.Find(14));
  EXPECT_TRUE(list.Find(13));
  EXPECT_FALSE(list.Empty());
  list.Print();
  EXPECT_EQ(list.Size(), static_cast<size_t>(5));
  EXPECT_EQ(list.Index(), 3);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 4);
  EXPECT_EQ(item, 13);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 0);
  EXPECT_EQ(item, 3);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 1);
  EXPECT_EQ(item, 3);
  list.Insert(14);
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(6));
  EXPECT_EQ(list.Index(), 1);
  list.Insert(3);
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(7));
  EXPECT_EQ(list.Index(), 1);
  list.Insert(2);
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(8));
  EXPECT_EQ(list.Index(), 1);
  list.Insert(13);
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(9));
  EXPECT_EQ(list.Index(), 1);
  EXPECT_TRUE(list.Remove(14));
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(8));
  list.Print();
  EXPECT_EQ(list.Index(), 1);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 2);
  EXPECT_EQ(item, 2);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 3);
  EXPECT_EQ(item, 13);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 4);
  EXPECT_EQ(item, 14);
  list.Print();
  EXPECT_TRUE(list.Remove(3));
  list.Print();
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(7));
  EXPECT_EQ(list.Index(), 3);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 4);
  EXPECT_EQ(item, 3);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 5);
  EXPECT_EQ(item, 2);
  EXPECT_TRUE(list.Remove(13));
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(6));
  EXPECT_EQ(list.Index(), 4);
  list.Next(&item);
  EXPECT_EQ(list.Index(), 5);
  EXPECT_EQ(item, 13);
  list.Print();
  list.Insert(17);
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(7));
  EXPECT_EQ(list.Index(), 5);
  list.Insert(7);
  EXPECT_FALSE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(8));
  EXPECT_EQ(list.Index(), 5);
  list.Print();
  list.Clear();
  list.Print();
  EXPECT_TRUE(list.Empty());
  EXPECT_EQ(list.Size(), static_cast<size_t>(0));
  EXPECT_EQ(list.Index(), -1);
}
